/*
 * Generated by genxface.pl - DO NOT EDIT!
 */
#ifdef __cplusplus
extern "C" {
#endif


//}

const char * essexeldUrlCheck(const char * url, unsigned urlLen) ;
void MD5_Init(MD5_CTX *ctx) ;
void MD5_Update(MD5_CTX *ctx, const void *data, unsigned long size) ;
void MD5_Final(unsigned char *result, MD5_CTX *ctx) ;

#ifdef __cplusplus
}
#endif
