/*
 * Generated by genxface.pl - DO NOT EDIT!
 */
#ifdef __cplusplus
extern "C" {
#endif

void essexeldUrlInit(const char * domainFile, const char * urlFile) ;
const char * essexeldUrlCheck(char * urlString, unsigned urlLength) ;
void MD5_Init(MD5_CTX *ctx) ;
void MD5_Update(MD5_CTX *ctx, const void *data, unsigned long size) ;
void MD5_Final(MD5 * result, MD5_CTX *ctx) ;
int md5Compare(const MD5 * left, const MD5 * right) ;

#ifdef __cplusplus
}
#endif
